### ISSUE TITLE
every time i hover over any kind of armor piece or tool my game crash

### ISSUE THREAD

**Issue by SolHTML** [AHilyard/LegendaryTooltips#161]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-11-08 22:17:41
Description: Rendering item

java.lang.AbstractMethodError: Receiver class com.anthonyhilyard.iceberg.fabric.services.FabricBufferSourceFactory$2$1 does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.minecraft.class_293)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at knot//net.caffeinemc.mods.sodium.client.render.immediate.model.BakedModelEncoder.writeQuadVertices(BakedModelEncoder.java:61)
	at knot//net.minecraft.class_918.renderBakedItemQuads(class_918.java:2595)
	at knot//net.minecraft.class_918.handler$dja000$sodium$renderModelFast(class_918.java:2573)
	at knot//net.minecraft.class_918.method_23182(class_918.java)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:474)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:323)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:648)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:373)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:155)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:664)
	at knot//com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:121)
	at knot//net.minecraft.class_332.method_51435(class_332.java:713)
	at knot//net.minecraft.class_332.method_51437(class_332.java:651)
	at knot//net.minecraft.class_465.method_2380(class_465.java:182)
	at knot//net.minecraft.class_481.method_25394(class_481.java:790)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$244(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bii000$fabric-screen-api-v1$onRenderScreen(class_757.java:4586)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.caffeinemc.mods.sodium.client.render.immediate.model.BakedModelEncoder.writeQuadVertices(BakedModelEncoder.java:61)
	at knot//net.minecraft.class_918.renderBakedItemQuads(class_918.java:2595)
	at knot//net.minecraft.class_918.handler$dja000$sodium$renderModelFast(class_918.java:2573)
	at knot//net.minecraft.class_918.method_23182(class_918.java)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:474)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:323)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:648)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:373)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:155)
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:664)
	at knot//com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:121)
	at knot//net.minecraft.class_332.method_51435(class_332.java:713)
	at knot//net.minecraft.class_332.method_51437(class_332.java:651)
	at knot//net.minecraft.class_465.method_2380(class_465.java:182)
	at knot//net.minecraft.class_481.method_25394(class_481.java:790)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$244(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bii000$fabric-screen-api-v1$onRenderScreen(class_757.java:4586)

-- Item being rendered --
Details:
	Item Type: minecraft:netherite_boots
	Item Components: {minecraft:max_damage=>481, minecraft:fire_resistant=>INSTANCE, minecraft:rarity=>COMMON, minecraft:attribute_modifiers=>class_9285[modifiers=[], showInTooltip=true], minecraft:max_stack_size=>1, minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}, minecraft:damage=>0, minecraft:lore=>class_9290[lines=[], styledLines=[]], minecraft:repair_cost=>0}
	Item Foil: false
Stacktrace:
	at knot//com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:664)
	at knot//com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:121)
	at knot//net.minecraft.class_332.method_51435(class_332.java:713)
	at knot//net.minecraft.class_332.method_51437(class_332.java:651)
	at knot//net.minecraft.class_465.method_2380(class_465.java:182)
	at knot//net.minecraft.class_481.method_25394(class_481.java:790)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$244(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bii000$fabric-screen-api-v1$onRenderScreen(class_757.java:4586)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (198, 173). Absolute: (794.000000, 695.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 144.350s
	Wall uptime: 137.169s
	High-res time: 135.410s
	Client ticks: 2459 ticks / 122.950s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:902)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['SolHTML'/65, l='ClientLevel', x=1116.60, y=62.94, z=586.26]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (1130,63,584), Section: (at 10,15,8 in 70,3,36; chunk contains blocks 1120,-64,576 to 1135,319,591), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,-64,512 to 1535,319,1023)
	Level time: 321757 game time, 81355 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 65

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, advancementplaques, ambientsounds, appleskin, autohud, betterf3, betterthirdperson, blur, bobby, cameraoverhaul, cardinal-components-base, cardinal-components-entity, cherishedworlds, chunksfadein, cicada, cloth-config, conditional-mixin, continuity, creativecore, disable_custom_worlds_advice, dynamic_fps, dynamiccrosshair, dynamiccrosshair-api, eatinganimationid, effecttimerplus, enhancedblockentities, entity_model_features, entity_texture_features, entityculling, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fastquit, firstperson, globalpacks, immediatelyfast, invmove, iris, lambdynlights, legendarytooltips, libbamboo, libzoomer, lithium, make_bubbles_pop, midnightlib, modmenu, moreculling, musicnotification, noisium, notenoughanimations, ok_zoomer, owo, panorama, particular, pride, prism, resourcify, showmeyourskin, skinlayers3d, sodium, sound_physics_remastered, spark, spruceui, tectonic, wrench_wrapper, yet_another_config_lib_v3, minecraft:supporteatinganimation, file/§eExtended_lantern_1.21x.zip, file/Better+Lanterns+v1.2-mc1.21.2.zip, file/§eTorches§8-§eReimagined§0_§8[v1.3.1]§0.zip, file/Shiny Trims v5 (Vanilla Animated).zip, file/Better_Enderdragon.zip, file/Immersive Realms Normal Water.zip, file/Compact Font.zip, continuity:default, continuity:glass_pane_culling_fix, file/Fresh Animations.zip, file/better Illagers vex fixed.zip, file/FA+Quivers-v1.1.zip, file/FA+Emissive-v1.2.zip, file/Expressive Fresh Moves v3.0.1.zip, file/LowOnFire_1.21.zip, file/Low Shield.zip, file/Fresh Skeleton Physics.zip, file/§eArmorstands-Reimagined§8-[v1.2].zip, musicnotification:dark_mode, file/DoorTweaks-v3.4.2.zip, file/crops-3d.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Mac OS X (aarch64) version 14.6.1
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 815791384 bytes (777 MiB) / 1577058304 bytes (1504 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 10
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2 Pro
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Avalanche + Blizzard
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 10
	Graphics card #0 name: Apple M2 Pro
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 19456.00
	Virtual memory used (MiB): 13899.09
	Swap memory total (MiB): 3072.00
	Swap memory used (MiB): 1815.50
	Space in storage for jna.tmpdir (MiB): available: 206617.55, total: 471482.09
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 206617.55, total: 471482.09
	Space in storage for io.netty.native.workdir (MiB): available: 206617.55, total: 471482.09
	Space in storage for java.io.tmpdir (MiB): available: 206617.55, total: 471482.09
	Space in storage for workdir (MiB): available: 206617.55, total: 471482.09
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.6.6
		ambientsounds: AmbientSounds 6.0.5
		appleskin: AppleSkin 3.0.5+mc1.21
		autohud: Auto HUD 7.2.1+1.21
		betterf3: BetterF3 11.0.1
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur+ (Fabric) 4.1.0
			midnightlib: MidnightLib 1.5.7
		bobby: Bobby 5.2.4+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		cherishedworlds: Cherished Worlds 10.1.0+1.21.1
		chunksfadein: Chunks Fade In 1.0.3-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		cicada: CICADA 0.8.3+1.21-and-above
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		creativecore: CreativeCore 2.12.6
			net_neoforged_bus: bus 7.2.0
		customskinloader: CustomSkinLoader 14.20
		disable_custom_worlds_advice: Disable Custom Worlds Advice 6.0
		dynamic_fps: Dynamic FPS 3.6.1
			net_lostluma_battery: battery 1.1.0
		dynamiccrosshair: Dynamic Crosshair 8.1+1.21
			dynamiccrosshair-api: DynamicCrosshair API 1.1
			libbamboo: libbamboo 1.21.0.2
		eatinganimationid: Eating Animation 1.21+1.9.71
		effecttimerplus: EffectTimerPlus 2.2.0
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fastquit: FastQuit 3.0.0+1.20.6
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.3
		globalpacks: Global Data- & Resourcepacks 21.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		iceberg: Iceberg 1.2.5
		immediatelyfast: ImmediatelyFast 1.3.1+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		invmove: InvMove 0.8.8
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lambdynlights: LambDynamicLights 3.1.2+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		legendarytooltips: Legendary Tooltips 1.4.11
		lithium: Lithium 0.12.5
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modmenu: Mod Menu 11.0.0
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moreculling: More Culling 1.0.0
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		mr_ships: Ships 3.0.3
		musicnotification: Music Notification 2.0.3
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		noisium: Noisium 2.2.1+mc1.21
		notenoughanimations: NotEnoughAnimations 1.7.4
		nullscape: Nullscape 1.2.7
		ok_zoomer: Ok Zoomer 9.0.2
			libzoomer: LibZoomer 0.10.0+1.21
			wrench_wrapper: Wrench Wrapper 0.4.0
		owo: oωo 0.12.11+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		panorama: Panorama 1.3.0
		particular: Particular 1.1.1+1.21
		prism: root project 'Prism' 1.0.9
		resourcify: Resourcify 1.5.1
		showmeyourskin: Show Me Your Skin! 1.11.3+1.21
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.5
		spark: spark 1.10.73
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		tectonic: Tectonic 2.4.0
		terralith: Terralith 2.5.3
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: BSLClassic_v8.3.zip
		Profile: MINIMUM (+57 options changed by user)
	Launched Version: fabric-loader-0.16.9-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Apple M2 Pro GL version 4.1 Metal - 88.1, Apple
	Window size: 1920x1080
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, advancementplaques, ambientsounds, appleskin (incompatible), autohud, betterf3, betterthirdperson, blur, bobby, cameraoverhaul, cardinal-components-base, cardinal-components-entity, cherishedworlds (incompatible), chunksfadein, cicada, cloth-config, conditional-mixin, continuity, creativecore, disable_custom_worlds_advice, dynamic_fps, dynamiccrosshair, dynamiccrosshair-api, eatinganimationid, effecttimerplus (incompatible), enhancedblockentities, entity_model_features, entity_texture_features, entityculling, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fastquit, firstperson, globalpacks (incompatible), immediatelyfast, invmove, iris, lambdynlights, legendarytooltips, libbamboo, libzoomer, lithium, make_bubbles_pop, midnightlib, modmenu, moreculling, musicnotification, noisium, notenoughanimations, ok_zoomer, owo, panorama, particular, pride, prism, resourcify (incompatible), showmeyourskin, skinlayers3d, sodium, sound_physics_remastered, spark (incompatible), spruceui, tectonic, wrench_wrapper, yet_another_config_lib_v3 (incompatible), minecraft:supporteatinganimation, file/§eExtended_lantern_1.21x.zip, file/Better+Lanterns+v1.2-mc1.21.2.zip (incompatible), file/§eTorches§8-§eReimagined§0_§8[v1.3.1]§0.zip (incompatible), file/Shiny Trims v5 (Vanilla Animated).zip (incompatible), file/Better_Enderdragon.zip (incompatible), file/Immersive Realms Normal Water.zip, file/Compact Font.zip (incompatible), continuity:default, continuity:glass_pane_culling_fix, file/Fresh Animations.zip, file/better Illagers vex fixed.zip (incompatible), file/FA+Quivers-v1.1.zip (incompatible), file/FA+Emissive-v1.2.zip, file/Expressive Fresh Moves v3.0.1.zip, file/LowOnFire_1.21.zip, file/Low Shield.zip, file/Fresh Skeleton Physics.zip, file/§eArmorstands-Reimagined§8-[v1.2].zip (incompatible), musicnotification:dark_mode, file/DoorTweaks-v3.4.2.zip, file/crops-3d.zip (incompatible)
	Current Language: en_us
	Locale: en_IL
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 10x Apple M2 Pro
	Server Running: true
	Player Count: 1 / 8; [class_3222['SolHTML'/65, l='ServerLevel[a classic village]', x=1116.60, y=62.94, z=586.26]]
	Active Data Packs: vanilla, fabric, dynamiccrosshair-api, fabric-convention-tags-v2, libzoomer, moreculling, mr_ships (incompatible), nullscape, ok_zoomer, terralith, terratonic (incompatible)
	Available Data Packs: vanilla, trade_rebalance, bundle, NoFun DnT v1.0.zip, Dungeons and Tavenrs v4.1.zip, fabric, dynamiccrosshair-api, fabric-convention-tags-v2, libzoomer, moreculling, mr_ships (incompatible), nullscape, ok_zoomer, terralith, terratonic (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -3571089688709297641

**Comment by Yaplay777** [comment]
Hey! I have that issue too! U found how to fix it?

**Comment by Yaplay777** [comment]
lemme just try can u remember what mods did u updated

**Comment by Yaplay777** [comment]
I asked on a minecraft forum and they said that iceberg conflicting with iris

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
