### ISSUE TITLE
1.21.1 Crash with sodium 0.6

### ISSUE THREAD

**Issue by IvanTopGaming** [AHilyard/LegendaryTooltips#164]
I have updated my mod pack with sodium to the latest version and when I hover the cursor over an item in the inventory, the game crashes
Error:
```
[18:19:05] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at knot/net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.anthonyhilyard.iceberg.fabric.services.FabricBufferSourceFactory$2$1 does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.minecraft.class_293)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at knot/net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.copyInto(VertexBufferWriter.java:96) ~[sodium-fabric-0.6.0+mc1.21.1.jar:?]
	at knot/net.minecraft.class_4720$class_4589.push(class_4720.java:542) ~[client-intermediary.jar:?]
	at knot/net.caffeinemc.mods.sodium.client.render.immediate.model.BakedModelEncoder.writeQuadVertices(BakedModelEncoder.java:61) ~[sodium-fabric-0.6.0+mc1.21.1.jar:?]
	at knot/net.minecraft.class_918.renderBakedItemQuads(class_918.java:2095) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_918.handler$dec000$sodium$renderModelFast(class_918.java:2073) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_918.method_23182(class_918.java) ~[client-intermediary.jar:?]
	at knot/com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:474) ~[Iceberg-1.21-fabric-1.2.6.jar:?]
	at knot/com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:323) ~[Iceberg-1.21-fabric-1.2.6.jar:?]
	at knot/com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:648) ~[Iceberg-1.21-fabric-1.2.6.jar:?]
	at knot/com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:373) ~[Iceberg-1.21-fabric-1.2.6.jar:?]
	at knot/com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:155) ~[Iceberg-1.21-fabric-1.2.6.jar:?]
	at knot/com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:664) ~[Iceberg-1.21-fabric-1.2.6.jar:?]
	at knot/com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:121) ~[LegendaryTooltips-1.21-fabric-1.4.11.jar:?]
	at knot/net.minecraft.class_332.redirect$dbk000$shulkerboxtooltip$drawPosAwareComponent(class_332.java:2828) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51435(class_332.java:713) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51437(class_332.java:651) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.shulkerboxtooltip$drawMouseoverTooltip(class_465.java:3732) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.shulkerboxtooltip$lockTooltipPosition(class_465.java:3322) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.redirect$dca000$shulkerboxtooltip$lockTooltipPosition(class_465.java:3726) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.method_2380(class_465.java:182) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_490.method_25394(class_490.java:86) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$method_47413$249(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$bll000$fabric-screen-api-v1$onRenderScreen(class_757.java:3086) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
```
My mods:
```
[18:18:24] [main/INFO]: Loading 194 mods:
	- architectury 13.0.6
	- betterstats 3.13.3+fabric-1.21
	- bobby 5.2.4+mc1.21
	   |-- com_typesafe_config 1.4.2
	   |-- fabric-api-base 0.4.42+6573ed8c6a
	   |-- fabric-command-api-v2 2.2.28+6ced4dd96a
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- c2me 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-base 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-client-uncapvd 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-fixes-chunkio-threading-issues 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-fixes-general-threading-issues 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-fixes-worldgen-threading-issues 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-notickvd 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-allocs 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-chunk-access 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-chunkio 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-dfc 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-math 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-natives-math 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-scheduling 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-worldgen-general 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-opts-worldgen-vanilla 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-rewrites-chunk-serializer 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-rewrites-chunk-system 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-rewrites-chunkio 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-server-utils 0.3.0+alpha.0.297+1.21.1
	   |-- c2me-threading-lighting 0.3.0+alpha.0.297+1.21.1
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- io_reactivex_rxjava3_rxjava 3.1.8
	   |-- mixinsquared 0.2.0-beta.6
	   |-- net_objecthunter_exp4j 0.4.8
	   |-- org_jctools_jctools-core 4.0.5
	   \-- org_reactivestreams_reactive-streams 1.0.4
	- clientcommands 2.9.3
	   |-- betterconfig 2.1.2
	   |-- clientarguments 1.9
	   \-- net_fabricmc_mapping-io 0.5.1
	- cloth-config 15.0.130
	   \-- cloth-basic-math 0.6.1
	- cmdkeybind 1.6.3-1.20.4
	   \-- kyrptconfig 1.6.0-1.20.4
	- continuity 3.0.0-beta.5+1.21
	- durabilityviewer 1.21-1.11.0
	- dynamic_fps 3.7.6
	   \-- net_lostluma_battery 1.3.0
	- dynamiccrosshair 8.1+1.21
	   |-- dynamiccrosshair-api 1.1
	   \-- libbamboo 1.21.0.2
	- e4mc_minecraft 5.2.1
	   \-- folk_sisby_kaleido-config 0.3.1+1.3.1
	- elytratime 2.1.0
	- enhancedblockentities 0.10.2+1.21
	- entityculling 1.7.1
	- fabric-api 0.108.0+1.21.1
	   |-- fabric-api-lookup-api-v1 1.6.70+b559734419
	   |-- fabric-biome-api-v1 13.0.30+be1ed2d719
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.18+b559734419
	   |-- fabric-convention-tags-v1 2.1.2+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.2+e60e56d419
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.3.0+8e331c5719
	   |-- fabric-data-generation-api-v1 20.2.23+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.1+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.5.0+01d9a51c19
	   |-- fabric-loot-api-v2 3.0.15+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.3+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.1+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.1+5b5275af19
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.2+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabric-language-kotlin 1.12.0+kotlin.2.0.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- ferritecore 7.0.2-hotfix
	- friendguard 2.1.5
	- gammautils 2.1.1
	- healthindicators 21.1.3
	- iceberg 1.2.6
	- iris 1.8.0+mc1.21.1
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- itemscroller 0.24.52
	- java 22
	- jei 19.21.0.247
	- krypton 0.2.8
	   \-- com_velocitypowered_velocity-native 3.3.0-SNAPSHOT
	- lambdynlights 3.1.2+1.21.1
	   |-- pride 1.2.1+1.21
	   \-- spruceui 5.1.0+1.21
	- legendarytooltips 1.4.11
	- libipn 6.0.2
	- lithium 0.14.2-snapshot+mc1.21.1-build.90
	- logical_zoom 0.0.26
	- malilib 0.21.1
	- minecraft 1.21.1
	- modmenu 11.0.3
	- placeholder-api 2.4.1+1.21
	- plasmovoice 2.1.1
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- prism 1.0.9
	- reeses-sodium-options 1.8.0+mc1.21.3
	- remote_player_waypoints_for_xaero 3.2.0
	- shulkerboxtooltip 5.1.2+1.21.1
	- sodium 0.6.0+mc1.21.1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   \-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	- sodium-extra 0.6.0+mc1.21.1
	- soundsbegone 1.3.5
	   \-- com_posthog_java_posthog 1.1.0
	- tcdcommons 3.12.3+fabric-1.21
	- viafabricplus 3.4.9
	   |-- com_github_oryxel_cubeconverter 5ae1e90e4f
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 5.1.2-SNAPSHOT
	   |-- com_viaversion_viaversion-common 5.1.2-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.1.1-SNAPSHOT
	   |-- io_jsonwebtoken_jjwt-api 0.12.6
	   |-- io_jsonwebtoken_jjwt-gson 0.12.6
	   |-- io_jsonwebtoken_jjwt-impl 0.12.6
	   |-- io_netty_netty-codec-http 4.1.114
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_commons_httpclient 1.6.0
	   |-- net_lenni0451_mcping 1.4.2
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.1
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.1
	   |-- net_lenni0451_reflect 1.3.4
	   |-- net_raphimc_minecraftauth 4.1.1
	   |-- net_raphimc_viaaprilfools-common 3.0.5-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.13-SNAPSHOT
	   |-- net_raphimc_vialegacy 3.0.6-SNAPSHOT
	   |-- net_raphimc_vialoader 3.0.5-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR3-SNAPSHOT
	   \-- org_lz4_lz4-pure-java 1.8.0
	- worldedit 7.3.8+6939-7d32b45
	- xaerominimap 24.6.1
	- xaeroworldmap 1.39.0
	- yet_another_config_lib_v3 3.6.1+1.21-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
```

**Comment by Nitroito** [comment]
updating Iceberg to version 1.2.7 solves the issue

i had the same issue and when reading this issue i spoted the root cause on your crash report

"Caused by: java.lang.AbstractMethodError: Receiver class com.anthonyhilyard.iceberg.fabric.services.FabricBufferSourceFactory$2$1 does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.minecraft.class_293)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
"

i updated the library and voila!! solved

**Comment by AHilyard** [comment]
Thank you, @Nitroito.  Sounds like this one is solved, so closing.
