### ISSUE TITLE
Crashes when opening config using mod menu below is the crash report

### ISSUE THREAD

**Issue by wemdne** [AHilyard/LegendaryTooltips#33]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2022/8/23 下午4:46
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because the return value of "net.minecraftforge.common.ForgeConfigSpec$ConfigValue.getScreenWidgetFactorySupplier()" is null
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntry.<init>(ConfigGuiScreen.java:514)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.handleConfigValue(ConfigGuiScreen.java:351)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$handleConfigValue$4(ConfigGuiScreen.java:340)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.handleConfigValue(ConfigGuiScreen.java:340)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$handleConfigValue$4(ConfigGuiScreen.java:340)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.handleConfigValue(ConfigGuiScreen.java:340)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$initializeConfigSpecification$1(ConfigGuiScreen.java:273)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.initializeConfigSpecification(ConfigGuiScreen.java:273)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$initializeEntries$0(ConfigGuiScreen.java:260)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.initializeEntries(ConfigGuiScreen.java:260)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.<init>(ConfigGuiScreen.java:231)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen.method_25426(ConfigGuiScreen.java:122)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$1(ModsScreen.java:135)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:448)
	at net.minecraft.class_310.method_1523(class_310.java:1171)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntry.<init>(ConfigGuiScreen.java:514)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.handleConfigValue(ConfigGuiScreen.java:351)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$handleConfigValue$4(ConfigGuiScreen.java:340)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.handleConfigValue(ConfigGuiScreen.java:340)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$handleConfigValue$4(ConfigGuiScreen.java:340)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.handleConfigValue(ConfigGuiScreen.java:340)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$initializeConfigSpecification$1(ConfigGuiScreen.java:273)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.initializeConfigSpecification(ConfigGuiScreen.java:273)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.lambda$initializeEntries$0(ConfigGuiScreen.java:260)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.initializeEntries(ConfigGuiScreen.java:260)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen$ConfigEntryList.<init>(ConfigGuiScreen.java:231)
	at net.minecraftforge.client.gui.config.widgets.ConfigGuiScreen.method_25426(ConfigGuiScreen.java:122)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$1(ModsScreen.java:135)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:448)
	at net.minecraft.class_310.method_1523(class_310.java:1171)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['oeH7uIW'/70, l='ClientLevel', x=38.80, y=60.11, z=-6.07]]
	Chunk stats: 961, 614
	Level dimension: minecraft:the_end
	Level spawn location: World: (-128,78,-16), Section: (at 0,14,0 in -8,4,-1; chunk contains blocks -128,0,-16 to -113,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1630240 game time, 878386 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:577)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, LMModelLoader, Invisible-Item-Frames-V4.zip, CMMRP+Release+1.0+-+[1.19+-+1.19.1]

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 12.4
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 964039048 bytes (919 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 12885.95
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 50.75
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 1.19-1.1.0-build.12
		architectury: Architectury 5.12.42
		attributefix: AttributeFix 15.1.3
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 4.2.0+0
		betterthirdperson: Better Third Person 1.8.1
		bookshelf: Bookshelf 14.2.10
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		cateyes: Cat Eyes 3.2.0
		cenchants: Combat Enchants 2.14.0
		chestcavity: Chest Cavity 2.16.3
			modify-drops-api: Modify Drops API 0.4.0.2
		cloth-config: Cloth Config v6 7.0.74
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+7
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		companion: Companion 3.0.0
		dark-enchanting: Dark Enchanting 1.0.0+1.19.1
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		diggusmaximus: Diggus Maximus 1.5.8-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		doublejump: Double Jump Mod 1.0.1+mc1.19
		dupetrigger: Dupe Trigger 1.11.13
		easyelytratakeoff-fabric: Easy Elytra Takeoff (Fabric) 2.3
		easymagic: Easy Magic 4.0.0
		eatinganimationid: Eating Animation 1.8.1
		effecttooltips: EffectTooltips 3.1.3
		elytraboosters: Elytra Boosters Mod 1.4.0
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchdesc: EnchantmentDescriptions 11.1.9
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricanvils: Fabric Anvils 3.0.0
		fabricloader: Fabric Loader 0.14.9
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.8
		forgeconfigapiport: Forge Config API Port 4.2.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		gilded: Gilded Netherite 1.0.2
		iceberg: Iceberg 1.0.38
		identity: Identity 2.5.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.1
		inventorytotem-fabric: Inventory Totem (Fabric) 1.7
		java: OpenJDK 64-Bit Server VM 17
		kiwi: Kiwi Lib 7.2.1
		legendarytooltips: Legendary Tooltips 1.2.5
		littlemaidmodelloader: LittleMaid ModelLoader 5.0.2
		littlemaidrebirth: LittleMaid ReBirth 5.0.4
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		noexpensive: NoExpensive 1.19-Fabric-1.4.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		optifabric: OptiFabric 1.13.10
			mm: Manningham Mills 2.3
		passiveshield-fabric: Passive Shield (Fabric) 2.1
		pehkui: Pehkui 3.4.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		potionring: Potion Ring - REFORGED 1.19-1.0
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		puzzleslib: Puzzles Lib 4.0.18
		roughlyenoughitems: Roughly Enough Items 9.1.530
			error_notifier: Error Notifier 1.0.9
		sit: Sit 1.19-20
		stacker: Stacker 3.0.2-1.19.x
			stacc: Stacc 1.3.4
		swordblocking: Sword Blocking 1.1.0
		tntbreaksbedrock-fabric: TNT Breaks Bedrock (Fabric) 2.0
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tooltipscroller: Tooltip Texts Scroller 1.0.0
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		trashslot: TrashSlot 12.0.1
		trinkets: Trinkets 3.4.0
		wthit: wthit 5.1.4
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
	Launched Version: fabric-loader-0.14.9-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M2 GL version 4.1 Metal - 76.3, Apple
	Window size: 2940x1840
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, littlemaidmodelloader (incompatible), file/Invisible-Item-Frames-V4.zip, file/CMMRP+Release+1.0+-+[1.19+-+1.19.1]
	Current Language: 简体中文 (中国大陆)
	CPU: 8x Apple M2
	Server Running: true
	Player Count: 1 / 8; [class_3222['oeH7uIW'/70, l='ServerLevel[新的世界]', x=38.80, y=60.11, z=-6.07]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	OptiFine Version: OptiFine_1.19_HD_U_H9
	OptiFine Build: 20220731-224510
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1 Metal - 76.3
	OpenGlRenderer: Apple M2
	OpenGlVendor: Apple
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19
	OptiFine jar version: OptiFine_1.19_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /Users/oeh6uiw/Library/Application Support/minecraft/.optifine/OptiFine_1.19_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there.  Thank you for understanding.
