### ISSUE TITLE
games crashes when hovering over a fishingrod

### ISSUE THREAD

**Issue by TheEntityb** [AHilyard/LegendaryTooltips#63]
sounds a bit ridiculously
but me and my friends were on a server and when the server restarted my friend got a fishing rod, we logged back onto the server and found out we would crash if we hovered over the fishing rod, but not in our hotbar, it would either be a chest or a enderchest or inventory, etc, but now we cant use fishing rods at all without deleting the mod, we have tried reinstalling multiple times and have even deleted .minecraft its self, but it still crashes 
(we are on fabric)

**Comment by AHilyard** [comment]
That's a weird one!  Could you post your crash log from one of the crashes for me?

**Comment by TheEntityb** [comment]
Time: 2023-04-16 20:22:28
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5321.method_29177()" because the return value of "net.minecraft.class_1937.method_27983()" is null
	at net.minecraft.class_906.handler$cch000$physicsmod$render(class_906.java:1075)
	at net.minecraft.class_906.method_3974(class_906.java)
	at net.minecraft.class_906.method_3936(class_906.java:21)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.lambda$renderEntityModel$0(CustomItemRenderer.java:174)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1164)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderEntityModel(CustomItemRenderer.java:174)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:281)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:603)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:348)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:153)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:621)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:95)
	at net.minecraft.class_437.redirect$cfj000$shulkerboxtooltip$drawPosAwareComponent(class_437.java:6258)
	at net.minecraft.class_437.method_32633(class_437.java:283)
	at net.minecraft.class_437.method_32634(class_437.java:193)
	at net.minecraft.class_481.method_25409(class_481.java:779)
	at net.minecraft.class_465.method_2380(class_465.java:188)
	at net.minecraft.class_481.method_25394(class_481.java:745)
	at net.minecraft.class_437.method_47413(class_437.java:113)
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by AHilyard** [comment]
Thank you for your report, this should be fixed in the latest Iceberg update: https://legacy.curseforge.com/minecraft/mc-mods/iceberg-fabric/files/4499763

**Comment by TheEntityb** [comment]
it says the page is closed

**Comment by TheEntityb** [comment]
not found* sorry

**Comment by TheEntityb** [comment]
is there a 1.19.3 verison?
