### ISSUE TITLE
Crash due to Iceberg

### ISSUE THREAD

**Issue by RosivDamotil** [AHilyard/LegendaryTooltips#67]
Today Iris, Sodium etc. were updated.
Now the game crashes when enabling Legendary Tooltips:

java.lang.IllegalArgumentException: The class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.createUnsupportedVertexConsumerThrowable(VertexBufferWriter.java:30)
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.of(VertexBufferWriter.java:22)
	at net.minecraft.class_4723.push(class_4723.java:541)
	at net.minecraft.class_630.method_22702(class_630.java:1083)
	at net.minecraft.class_630.method_22699(class_630.java:124)
	at net.minecraft.class_756.method_3166(class_756.java:158)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:315)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:618)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:361)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:154)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:636)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111)
	at net.minecraft.class_437.method_32633(class_437.java:325)
	at net.minecraft.class_437.method_32634(class_437.java:245)
	at net.minecraft.class_437.method_25409(class_437.java:236)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_490.method_25394(class_490.java:96)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by AHilyard** [comment]
Thank you for letting me know, I will try getting this solved soon.

**Comment by AHilyard** [comment]
This has been fixed in Iceberg version 1.1.10.

**Comment by RosivDamotil** [comment]
Thx! :)
