### ISSUE TITLE
Somehow... it's broken again.... (Iceberg and Sodium)

### ISSUE THREAD

**Issue by RosivDamotil** [AHilyard/LegendaryTooltips#69]
java.lang.ClassCastException: class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.anthonyhilyard.iceberg.renderer.VertexCollector$1 and me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @97e1986)
	at me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter.of(VertexBufferWriter.java:8)
	at net.minecraft.class_4723.push(class_4723.java:539)
	at net.minecraft.class_630.method_22702(class_630.java:1611)
	at net.minecraft.class_630.method_22699(class_630.java:124)
	at net.minecraft.class_756.method_3166(class_756.java:158)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:315)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:618)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:361)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:154)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:636)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111)
	at net.minecraft.class_437.method_32633(class_437.java:325)
	at net.minecraft.class_437.method_32634(class_437.java:245)
	at net.minecraft.class_437.method_25409(class_437.java:236)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_490.method_25394(class_490.java:96)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by Dphill10827** [comment]
Same issue for me on 1.19.4, crash log here: https://pastebin.com/vdQEwxUK

**Comment by DiamoaletyPL** [comment]
same issue for me (1.19.4)

**Comment by McSkinnerOG** [comment]
yep exact same issue here... same error: https://hastebin.com/share/omuxojolow.yaml

**Comment by AHilyard** [comment]
Sorry everyone, it has been hard maintaining compatibility with Sodium.
What you are experiencing is an incompatibility between version 1.1.10 of Iceberg and Sodium version 0.4.10. Version 1.1.10 of Iceberg was designed for version 0.4.11 of Sodium, but that version has been removed. 
I have now archived version 1.1.10 of Iceberg on Fabric, so if you are still on that version please downgrade to an older version to fix this.
