### ISSUE TITLE
Crash when hovering over wooden axe

### ISSUE THREAD

**Issue by xXCensoriousXx** [AHilyard/LegendaryTooltips#70]
game crashes immediately after hovering mouse over the wooden axe

Time: 2023-05-11 02:49:23
Description: Rendering item

java.lang.ClassCastException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:641)

-- Item being rendered --
Details:
	Item Type: wooden_axe
	Registry Name: minecraft:wooden_axe
	Item Damage: 51
	Item NBT: {Damage:51}
	Item Foil: false
Stacktrace:
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:641)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111)
	at net.minecraft.class_437.method_32633(class_437.java:325)
	at net.minecraft.class_437.method_32634(class_437.java:245)
	at net.minecraft.class_437.method_25409(class_437.java:236)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_490.method_25394(class_490.java:96)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by AHilyard** [comment]
If you're on 1.19.4, please downgrade Iceberg to fix this issue.  If that doesn't work feel free to reopen this.
