### ISSUE TITLE
Rendering Item Issue

### ISSUE THREAD

**Issue by Pdam67** [AHilyard/LegendaryTooltips#73]
[22:04:54] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.anthonyhilyard.iceberg.renderer.VertexCollector$1 and me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5702b3b1)
	at me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter.of(VertexBufferWriter.java:8) ~[sodium-fabric-mc1.19.4-0.4.10+build.24.jar:?]
	at net.minecraft.class_918.method_23182(class_918.java:1042) ~[client-intermediary.jar:?]
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:476) ~[Iceberg-1.19.4-fabric-1.1.10.jar:?]
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:310) ~[Iceberg-1.19.4-fabric-1.1.10.jar:?]
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:618) ~[Iceberg-1.19.4-fabric-1.1.10.jar:?]
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:361) ~[Iceberg-1.19.4-fabric-1.1.10.jar:?]
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:154) ~[Iceberg-1.19.4-fabric-1.1.10.jar:?]
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:636) ~[Iceberg-1.19.4-fabric-1.1.10.jar:?]
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111) ~[LegendaryTooltips-1.19.4-fabric-1.4.3.jar:?]
	at net.minecraft.class_437.method_32633(class_437.java:325) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_32634(class_437.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25409(class_437.java:236) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2380(class_465.java:179) ~[client-intermediary.jar:?]
	at net.minecraft.class_476.method_25394(class_476.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:937) ~[client-intermediary.jar:?]
	... 9 more
---- Minecraft Crash Report ----
// Shall we play a game?
Time: 2023-05-21 22:04:54
Description: Rendering item
java.lang.ClassCastException: class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.anthonyhilyard.iceberg.renderer.VertexCollector$1 and me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5702b3b1)
	at me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter.of(VertexBufferWriter.java:8)
	at net.minecraft.class_918.method_23182(class_918.java:1042)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:476)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:310)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:618)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:361)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:154)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:636)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111)
	at net.minecraft.class_437.method_32633(class_437.java:325)
	at net.minecraft.class_437.method_32634(class_437.java:245)
	at net.minecraft.class_437.method_25409(class_437.java:236)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_476.method_25394(class_476.java:31)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter.of(VertexBufferWriter.java:8)
	at net.minecraft.class_918.method_23182(class_918.java:1042)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:476)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:310)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:618)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:361)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:154)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:636)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111)
	at net.minecraft.class_437.method_32633(class_437.java:325)
	at net.minecraft.class_437.method_32634(class_437.java:245)
	at net.minecraft.class_437.method_25409(class_437.java:236)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_476.method_25394(class_476.java:31)
	at net.minecraft.class_437.method_47413(class_437.java:121)
-- Item being rendered --
Details:
	Item Type: golden_boots
	Registry Name: minecraft:golden_boots
	Item Damage: 0
	Item NBT: {Damage:0,HideFlags:2,display:{Lore:['{"italic":false,"text":""}','{"italic":false,"extra":[{"color":"gray","text":"Go to a random running server!"}],"text":""}'],Name:'{"italic":false,"extra":[{"color":"green","text":"Join a Random Server"}],"text":""}'}}
	Item Foil: false
Stacktrace:
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:636)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:111)
	at net.minecraft.class_437.method_32633(class_437.java:325)
	at net.minecraft.class_437.method_32634(class_437.java:245)
	at net.minecraft.class_437.method_25409(class_437.java:236)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_476.method_25394(class_476.java:31)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Screen render details --
Details:
	Screen name: net.minecraft.class_476
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Affected level --
Details:
	All players: 21 total; [class_746['Pdam67'/6523, l='ClientLevel', x=53.32, y=64.50, z=-6.73], class_745[' '/116, l='ClientLevel', x=36.50, y=62.00, z=0.50], class_745['highlighterlife'/5721, l='ClientLevel', x=54.12, y=67.00, z=-21.46], class_745['BlackD3stiny'/6447, l='ClientLevel', x=48.24, y=62.44, z=6.19], class_745['CIT-7275e9c2a564'/147, l='ClientLevel', x=65.50, y=62.00, z=7.50], class_745['SeriousSwimmerr'/6433, l='ClientLevel', x=55.53, y=130.56, z=-30.53], class_745['CIT-d39261fa8b8c'/94, l='ClientLevel', x=45.50, y=63.00, z=8.50], class_745['CIT-7d45b7facf3d'/143, l='ClientLevel', x=49.50, y=63.00, z=9.50], class_745['§a[Get Ranks]'/140, l='ClientLevel', x=57.50, y=63.00, z=9.50], class_745['MinecraftMint'/6487, l='ClientLevel', x=65.75, y=62.50, z=-9.92], class_745['shgleep'/5813, l='ClientLevel', x=68.50, y=62.00, z=4.50], class_745[' '/106, l='ClientLevel', x=39.50, y=63.00, z=6.50], class_745[' '/121, l='ClientLevel', x=33.50, y=63.00, z=0.50], class_745[' '/126, l='ClientLevel', x=33.50, y=62.00, z=-2.50], class_745[' '/111, l='ClientLevel', x=42.50, y=62.00, z=6.50], class_745['CIT-820d141e5cfb'/136, l='ClientLevel', x=61.50, y=63.00, z=8.50], class_745['sys1em_err0r'/6443, l='ClientLevel', x=54.71, y=63.50, z=-5.02], class_745[' '/101, l='ClientLevel', x=39.50, y=62.00, z=3.50], class_745['bellzz_loll'/6515, l='ClientLevel', x=55.19, y=63.50, z=-4.58], class_745['friendofdogs'/6511, l='ClientLevel', x=51.30, y=66.50, z=-17.11], class_745['Freehawk4123'/6531, l='ClientLevel', x=54.06, y=63.00, z=2.76]]
	C
hunk stats: 1024, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,4,0), Section: (at 0,4,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10199001 game time, 6000 day time
	Server brand: Minehut/Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, server
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 414178032 bytes (394 MiB) / 889192448 bytes (848 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.07
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.07
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31153.77
	Virtual memory used (MB): 20444.00
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 352.37
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.81.1+1.19.4
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.27+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.36+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.17+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.29+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.8+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.46+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.56+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.11+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.1+fe8721bef4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.2+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.47+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.15+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.1+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.54+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.19+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.7+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.17+1e9487d2f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.3+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.41+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.32+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.43+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.5+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.25+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.10+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.2+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.7+ebc93ff3f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.2.0+ebc93ff3f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.40+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.30+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.23+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.43+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.22+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.0+80d07a0af4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.1.1+b4a333d6f4
		fabricloader: Fabric Loader 0.14.19
		forgeconfigapiport: Forge Config API Port 6.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		iceberg: Iceberg 1.1.10
		java: OpenJDK 64-Bit Server VM 17
		legendarytooltips: Legendary Tooltips 1.4.3
		minecraft: Minecraft 1.19.4
		prism: Prism 1.0.4
		sodium: Sodium 0.4.10+build.24
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 4x AMD Ryzen 3 3200G with Radeon Vega Graphics 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Massimo D'Ambrosio\AppData\Roaming\PrismLauncher\instances\temp\.minecraft\crash-reports\crash-2023-05-21_22.04.54-client.txt
Process exited with code -1.

----
Replicatable with:
The mod and it's dependencies on the latest versions
Sodium 0.4.10 build 24
Fabric API (Latest)
Fabric Loader (Latest)

I think it's caused by an item with bad NBT data.

**Comment by AHilyard** [comment]
I believe what you are experiencing is an incompatibility between version 1.1.10 of Iceberg and Sodium version 0.4.10.  Version 1.1.10 of Iceberg was designed for version 0.4.11 of Sodium, but that version has been removed.  Please downgrade Iceberg to an older version to fix this.
